CREATE TABLE Engineering.SystemTemperatureSetPoint(
    TemperatureSetPointId INT PRIMARY KEY,
    AftercoolerInlet INT,
    AftercoolerOutlet INT,
    ColumnAverage INT,
    ColumnBottom INT,
    ColumnMiddle INT,
    ColumnMiddleSetPoint INT,
    ColumnTop INT,
    CondenserInlet INT,
    CondenserOutlet INT,
    CondenserSkin INT,
    CondeserTop INT,
    HeatingTop INT,
    HeatingTopSkin INT,
    Liquid INT,
    LN2VacuumTraps INT,
    ReboilerZone1 INT,
    ReboilerZone2 INT,
    ReboilerZone3 INT,
    ReboilerZone4 INT,
    ReboilerZone5 INT,
    ReboilerZone6 INT,
    RefluxSplitter INT,
    TopColumn INT,
    ControllerZone1 INT,
    ControllerZone2 INT,
    ControllerZone3 INT
    )