//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RLRMWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialNumber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaterialNumber()
        {
            this.Products = new HashSet<Product>();
            this.MaterialIds = new HashSet<MaterialId>();
            this.RawMaterialLogs = new HashSet<RawMaterialLog>();
            this.VendorBatches = new HashSet<VendorBatch>();
        }
    
        public int MaterialNumber1 { get; set; }
        public Nullable<int> NameId { get; set; }
        public Nullable<bool> BatchManaged { get; set; }
        public Nullable<bool> RequiresProcessOrder { get; set; }
        public string UnitOfIssue { get; set; }
        public Nullable<bool> IsRawMaterial { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        public virtual Material Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialId> MaterialIds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RawMaterialLog> RawMaterialLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorBatch> VendorBatches { get; set; }
    }
}
