//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RLRMWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialId
    {
        public int MaterialId1 { get; set; }
        public Nullable<int> MaterialNumber { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> SequenceId { get; set; }
        public Nullable<int> CurrentSequenceId { get; set; }
    
        public virtual MaterialNumber MaterialNumber1 { get; set; }
    }
}
