//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RLRMWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.MaterialNumbers = new HashSet<MaterialNumber>();
        }
    
        public int NameId { get; set; }
        public string MaterialName { get; set; }
        public string MaterialNameAbreviation { get; set; }
        public string PermitNumber { get; set; }
        public string RawMaterialCode { get; set; }
        public string ProductCode { get; set; }
        public Nullable<bool> CarbonDrumRequired { get; set; }
        public Nullable<int> CarbonDrumDaysAllowed { get; set; }
        public Nullable<int> CarbonDrumWeightAllowed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialNumber> MaterialNumbers { get; set; }
    }
}
