//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RLRMWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class materialId
    {
        public int materialId1 { get; set; }
        public Nullable<int> materialNumber { get; set; }
        public Nullable<int> vendorId { get; set; }
        public Nullable<int> sequenceId { get; set; }
        public Nullable<int> currentSequenceId { get; set; }
    
        public virtual materialNumber materialNumber1 { get; set; }
    }
}
