//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RLRMWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class materialNumber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public materialNumber()
        {
            this.materialIds = new HashSet<materialId>();
            this.products = new HashSet<product>();
            this.rawMaterials = new HashSet<rawMaterial>();
            this.vendorBatchInformations = new HashSet<vendorBatchInformation>();
        }
    
        public int materialNumber1 { get; set; }
        public int materialNameId { get; set; }
        public bool batchManaged { get; set; }
        public bool requiresProcessOrder { get; set; }
        public string unitOfIssue { get; set; }
        public bool isRawMaterial { get; set; }
    
        public virtual material material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<materialId> materialIds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product> products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rawMaterial> rawMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vendorBatchInformation> vendorBatchInformations { get; set; }
    }
}
