//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RLRMWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductNumberSequence
    {
        public int SequenceId { get; set; }
        public int SequenceIdStart { get; set; }
        public Nullable<int> SequenceIdEnd { get; set; }
    }
}
