//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RLRMWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class productNumberSequence
    {
        public int sequenceId { get; set; }
        public int sequenceIdStart { get; set; }
        public Nullable<int> sequenceIdEnd { get; set; }
    }
}
