//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RLRMWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.UsageLogs = new HashSet<UsageLog>();
        }
    
        public string ProductLotNumber { get; set; }
        public Nullable<int> MaterialNumber { get; set; }
        public Nullable<int> ProductionBatchNumber { get; set; }
        public Nullable<decimal> ProcessOrder { get; set; }
        public Nullable<int> ReceiverId { get; set; }
        public string SampleSubmitNumber { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual MaterialNumber MaterialNumber1 { get; set; }
        public virtual Receiver Receiver { get; set; }
        public virtual SampleSubmit SampleSubmit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsageLog> UsageLogs { get; set; }
    }
}
