//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RLRMWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterialLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RawMaterialLog()
        {
            this.UsageLogs = new HashSet<UsageLog>();
        }
    
        public string DrumLotNumber { get; set; }
        public Nullable<int> MaterialNumber { get; set; }
        public Nullable<int> DrumWeight { get; set; }
        public Nullable<int> SapBatchNumber { get; set; }
        public string ContainerNumber { get; set; }
        public string SampleSubmitNumber { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> VendorBatchId { get; set; }
        public System.DateTime DateUsed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsageLog> UsageLogs { get; set; }
        public virtual MaterialNumber MaterialNumber1 { get; set; }
        public virtual SampleSubmit SampleSubmit { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual VendorBatch VendorBatch { get; set; }
    }
}
