//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RLRMWF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RLRMDBEntities : DbContext
    {
        public RLRMDBEntities()
            : base("name=RLRMDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<alphabeticDate> alphabeticDates { get; set; }
        public virtual DbSet<distilation> distilations { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<material> materials { get; set; }
        public virtual DbSet<materialId> materialIds { get; set; }
        public virtual DbSet<materialNumber> materialNumbers { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<productNumberSequence> productNumberSequences { get; set; }
        public virtual DbSet<qualityControl> qualityControls { get; set; }
        public virtual DbSet<rawMaterial> rawMaterials { get; set; }
        public virtual DbSet<receiver> receivers { get; set; }
        public virtual DbSet<vendor> vendors { get; set; }
        public virtual DbSet<vendorBatchInformation> vendorBatchInformations { get; set; }
    }
}
