//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RLRMWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorBatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VendorBatch()
        {
            this.RawMaterialLogs = new HashSet<RawMaterialLog>();
        }
    
        public int BatchId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string VendorBatchNumber { get; set; }
        public string SampleSubmitNumber { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> MaterialNumber { get; set; }
    
        public virtual MaterialNumber MaterialNumber1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RawMaterialLog> RawMaterialLogs { get; set; }
        public virtual SampleSubmit SampleSubmit { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
