CREATE TABLE Distillation.SystemTemperatureSetPoint(
    TemperatureSetPointId INT,
    ReboilerZone1 INT,
    ReboilerZone2 INT,
    ReboilerZone3 INT,
    ReboilerZone4 INT,
    ReboilerZone5 INT,
    ReboilerZone6 INT,
    ColumnAverage INT,
    InternalFluidTemp INT,
    ColumnBottom INT,
    ColumnMiddle INT,
    ColumnTop INT,
    RefluxSplitter INT,
    CondenserTop INT,
    CondenserCoolantOutlet INT,
    AftercoolerCoolantOutlet INT,
    CondeserSkin INT,
    CondenserInlet INT,
    AftercoolerInlet INT,
    LN2 INT,
)