//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RLRMWF.Tests
{
    using System;
    using System.Collections.Generic;
    
    public partial class distilation
    {
        public int productId { get; set; }
        public string productLotNumber { get; set; }
        public string drumLotNumber { get; set; }
        public Nullable<int> rawMaterialLoaded { get; set; }
        public Nullable<int> prefraction { get; set; }
        public Nullable<int> heels { get; set; }
        public bool heelsPumped { get; set; }
        public Nullable<int> runNumber { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
    
        public virtual rawMaterial rawMaterial { get; set; }
        public virtual product product { get; set; }
    }
}
