//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RLRMWF.Tests
{
    using System;
    using System.Collections.Generic;
    
    public partial class material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public material()
        {
            this.materialNumbers = new HashSet<materialNumber>();
        }
    
        public int materialNameId { get; set; }
        public string materialName { get; set; }
        public string materialNameAbreviation { get; set; }
        public string permitNumber { get; set; }
        public string rawMaterialCode { get; set; }
        public string productCode { get; set; }
        public bool carbonDrumRequired { get; set; }
        public Nullable<int> carbonDrumDaysAllowed { get; set; }
        public Nullable<int> carbonDrumWeightAllowed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<materialNumber> materialNumbers { get; set; }
    }
}
