//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RLRMWF.Tests
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.distilations = new HashSet<distilation>();
        }
    
        public string productLotNumber { get; set; }
        public Nullable<int> materialNumber { get; set; }
        public Nullable<int> productionBatchNumber { get; set; }
        public Nullable<decimal> processOrder { get; set; }
        public Nullable<int> receiverId { get; set; }
        public string sampleSubmitNumber { get; set; }
        public Nullable<int> quantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<distilation> distilations { get; set; }
        public virtual materialNumber materialNumber1 { get; set; }
        public virtual qualityControl qualityControl { get; set; }
    }
}
