//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RLRMWF.Tests
{
    using System;
    using System.Collections.Generic;
    
    public partial class rawMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rawMaterial()
        {
            this.distilations = new HashSet<distilation>();
        }
    
        public string drumLotNumber { get; set; }
        public Nullable<int> materialNumber { get; set; }
        public Nullable<int> drumWeight { get; set; }
        public Nullable<int> sapBatchNumber { get; set; }
        public string containerNumber { get; set; }
        public string sampleSubmitNumber { get; set; }
        public Nullable<decimal> processOrder { get; set; }
        public Nullable<int> vendorId { get; set; }
        public Nullable<int> vendorBatchId { get; set; }
        public System.DateTime dateUsed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<distilation> distilations { get; set; }
        public virtual materialNumber materialNumber1 { get; set; }
        public virtual qualityControl qualityControl { get; set; }
        public virtual vendor vendor { get; set; }
        public virtual vendorBatchInformation vendorBatchInformation { get; set; }
    }
}
