//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RLRMWF.Tests
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendorBatchInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vendorBatchInformation()
        {
            this.qualityControls = new HashSet<qualityControl>();
            this.rawMaterials = new HashSet<rawMaterial>();
        }
    
        public int batchId { get; set; }
        public Nullable<int> vendorId { get; set; }
        public string vendorBatchNumber { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> materialNumber { get; set; }
    
        public virtual materialNumber materialNumber1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qualityControl> qualityControls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rawMaterial> rawMaterials { get; set; }
        public virtual vendor vendor { get; set; }
    }
}
