name: SqlServer2019

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: docker
      - name: Build the Docker image
      - image: DockerFile

          run: docker build . --file ./Dockerfile
